### ISSUE TITLE
use ncurses 5.9 causes conflict with libedit with conda

### ISSUE THREAD

**Issue by wenzhenl** [conda-forge/tmux-feedstock#4] opened 2017-10-26 02:48 UTC
Fetching package metadata .............
Solving package specifications: 

UnsatisfiableError: The following specifications were found to be in conflict:
  - libedit -> ncurses 6.0.*
  - tmux -> ncurses 5.9
Use "conda info <package>" to see the dependencies for each package.

**Comment by jakirkham** [comment] 2017-10-26 13:38
There's not enough information here to know, but it is probably because you have `defaults` copy of `libedit` installed. Please either use a fresh environment or remove `libedit` and retry.

In any event this is not a bug with `tmux`. Though it is arguable a bug with `conda`, which IIUC should be fixed in `conda` 4.4.0.

**Closed** 2017-10-26 13:38 UTC
